name: test
on:
  pull_request:
  push:
    branches:
      - main
      - release/*
defaults:
  run:
    shell: bash
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {os: ubuntu-latest,  python-version: "3.6"}
          - {os: ubuntu-latest,  python-version: "3.7"}
          - {os: ubuntu-latest,  python-version: "3.8"}
          - {os: ubuntu-latest,  python-version: "3.9"}
          - {os: ubuntu-latest,  python-version: "3.10"}
          - {os: windows-latest, python-version: "3.10"}
          - {os: macos-latest,   python-version: "3.10"}
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install SI module, numpy, pytest
      run: python3 -m pip install . numpy pytest-cov
    - name: Test & generate coverage report
      run: pytest --cov=./ --cov-report=xml --doctest-glob="*.md"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/reports/
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        verbose: true
